name: Release candidate
run-name: Release candidate ${{ github.event.inputs.release-candidate-version }}

on:
  workflow_dispatch:
    inputs:
      release-candidate-version:
        description: 'Release candidate version in format rX.X.X'
        required: true
      cosmos-version:
        description: 'Cosmos service version in format vX.X.X'
        required: true
        default: latest
      hubble-version:
        description: 'Cosmos service version in format vX.X.X'
        required: true
        default: latest
      stardust-version:
        description: 'Cosmos service version in format vX.X.X'
        required: true
        default: latest
      frontier-version:
        description: 'Cosmos service version in format vX.X.X'
        required: true
        default: latest
      nebula-version:
        description: 'Cosmos service version in format vX.X.X'
        required: true
        default: latest
      choice-env:
        type: choice
        description: Choose environment
        options:
          - Staging
          - Production
jobs:
  test:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4