name: Release candidate
run-name: Release candidate ${{ github.event.inputs.release-candidate-version }}

on:
  workflow_dispatch:
    inputs:
      release-candidate-version:
        description: 'Release candidate version in format rX.X.X'
        required: true
      cosmos-version:
        description: 'Cosmos service version in format vX.X.X'
      hubble-version:
        description: 'Cosmos service version in format vX.X.X'
      stardust-version:
        description: 'Cosmos service version in format vX.X.X'
      frontier-version:
        description: 'Cosmos service version in format vX.X.X'
      nebula-version:
        description: 'Cosmos service version in format vX.X.X'
jobs:
  test:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4