name: Release service
run-name: Release service ${{ github.event.inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        default: ""

jobs:
  test:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4